theme: jekyll-theme-slate
Title: Welcome to my GitHub page
Description: this webpage is probably meant as like a resume or something, however due to my 12 year old mind, i will most likely use it as a place to collect dumb jokes.
